package priv.dbs.model;
// Generated 2017-3-11 21:16:57 by Hibernate Tools 5.2.1.Final

/**
 * Movie generated by hbm2java
 */
public class Movie implements java.io.Serializable {

	private Integer id;
	private String title;
	private String directors;
	private String writers;
	private String casts;
	private String genres;
	private String countries;
	private String languages;
	private String pubdates;
	private String durations;
	private String aka;
	private String summary;
	private Float rating;
	private Integer ratingCount;
	private String imageUrl;

	public Movie() {
	}

	public Movie(String title, String directors, String writers, String casts, String genres, String countries,
			String languages, String pubdates, String durations, String aka, String summary, Float rating,
			Integer ratingCount, String imageUrl) {
		this.title = title;
		this.directors = directors;
		this.writers = writers;
		this.casts = casts;
		this.genres = genres;
		this.countries = countries;
		this.languages = languages;
		this.pubdates = pubdates;
		this.durations = durations;
		this.aka = aka;
		this.summary = summary;
		this.rating = rating;
		this.ratingCount = ratingCount;
		this.imageUrl = imageUrl;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDirectors() {
		return this.directors;
	}

	public void setDirectors(String directors) {
		this.directors = directors;
	}

	public String getWriters() {
		return this.writers;
	}

	public void setWriters(String writers) {
		this.writers = writers;
	}

	public String getCasts() {
		return this.casts;
	}

	public void setCasts(String casts) {
		this.casts = casts;
	}

	public String getGenres() {
		return this.genres;
	}

	public void setGenres(String genres) {
		this.genres = genres;
	}

	public String getCountries() {
		return this.countries;
	}

	public void setCountries(String countries) {
		this.countries = countries;
	}

	public String getLanguages() {
		return this.languages;
	}

	public void setLanguages(String languages) {
		this.languages = languages;
	}

	public String getPubdates() {
		return this.pubdates;
	}

	public void setPubdates(String pubdates) {
		this.pubdates = pubdates;
	}

	public String getDurations() {
		return this.durations;
	}

	public void setDurations(String durations) {
		this.durations = durations;
	}

	public String getAka() {
		return this.aka;
	}

	public void setAka(String aka) {
		this.aka = aka;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public Float getRating() {
		return this.rating;
	}

	public void setRating(Float rating) {
		this.rating = rating;
	}

	public Integer getRatingCount() {
		return this.ratingCount;
	}

	public void setRatingCount(Integer ratingCount) {
		this.ratingCount = ratingCount;
	}

	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

}
